class CfgFunctions
{
	class KH_Functions
	{
		tag = "KH";
		class KH_Framework
		{
			file = "\x\kh\addons\main\functions";
			class addEventHandler {};
			class arma {};
			class assignIdentificationCard {};
			class assignParachute {};
			class assignTerminal {};
			class breakDisguise {};
			class callParsedFunction {};
			class cameraSequence {};		
			class closeInterface {};
			class conditionalPresence {};
			class contextMenu {};
			class convertToAgent {};
			class convertToSimpleObject {};
			class deleteArrayElements {};
			class diagnostics {};
			class displaySubtitle {};
			class draw2d {};
			class draw3d {};
			class dynamic2dAudio {};
			class dynamic3dAudio {};
			class dynamicDisguise {};
			class editTerrainObjects {};
			class endMission {};
			class entitySpawner {};
			class equipableObject {};
			class execute {};
			class fultonExtract {};
			class getConfigValue {};
			class getDestinationTime {};
			class getDestinationVelocity {};
			class getEntityAreaPresence {};
			class getEntityByIdentifier {};
			class getEntityVariableName {};
			class getGroupAttributes {};
			class getMissionAttributes {};
			class getObjectAttributes {};
			class getObjectInventory {};
			class getPositionScreenRatio {};
			class getScreenVisiblePositions {};
			class getUnitAttributes {};
			class getUnitVehicleSlot {};
			class getVehicleLoadout {};
			class getViewTarget {};
			class getWeaponPosition {};
			class getWeaponTarget {};
			class limitViewDistance {};
			class loadObjectInventories {};
			class loadControlAttributes {};
			class loadDisplay {};
			class loadMissionState {};
			class loadPlayerLoadouts {};
			class log {};
			class luaRecompile {};
			class moduleCameraSequence {};
			class moduleDynamicDisguiseEquipment {};
			class moduleEditTerrainObjects {};
			class moduleEndMission {};
			class moduleEntitySpawner {};
			class openIdentificationCard {};
			class openTerminal {};
			class parseBoolean {};
			class parseFunction {};
			class parseNormalizedScreenTransforms {};
			class postInit {postInit = 1;};
			class preInit {preInit = 1;};
			class preStart {preStart = 1;};
			class raycast {};
			class raycast2d {};
			class raycast3d {};
			class recoverDisconnectedPlayers {};
			class remoteExec {};
			class removeEventHandler {};
			class removeHandler {};
			class respawnSpectator {};
			class saveObjectInventories {};
			class saveControlAttributes {};
			class saveMissionState {};
			class savePlayerLoadouts {};
			class screenToWorld {};
			class setCameraTexture {};
			class setCurators {};
			class setDestinationVelocity {};
			class setEntityVariableName {};
			class setGroupAttributes {};
			class setOwnership {};
			class setMissionAttributes {};
			class setObjectAttributes {};
			class setObjectInventory {};
			class setPerspective {};
			class setRating {};
			class setSideRelations {};
			class setTerminalText {};
			class setUnitAttributes {};
			class setUnitVehicleSlot {};
			class setVehicleLoadout {};
			class setVideoTexture {};
			class teleport {};
			class toggleUserInput {};
			class triggerCbaEvent {};
			class unconsciousSpectator {};
			class vehicleSequence {};
			class visualTrigger {};
			class zeusModuleArma {};
			class zeusModuleBreakDisguise {};
			class zeusModuleRagdollUnit {};
		};
	};
};