class CfgFunctions
{
	class KH_Functions
	{
		tag = "KH";
		class KH_Framework
		{
			file = "\x\kh\addons\main\functions";
			class addEventHandler {};
			class addRemoteInteractionEntry {};
			class addSelfInteractionEntry {};
			class arma {};
			class arraySum {};
			class assignIdentificationCard {};
			class assignParachute {};
			class assignTerminal {};
			class atomicValue {};
			class atomicVariable {};
			class cameraSequence {};		
			class closeInterface {};
			class conditionalPresence {};
			class contextMenu {};
			class convertToAgent {};
			class convertToSimpleObject {};
			class diagnostics {};
			class displaySubtitle {};
			class dynamic2dAudio {};
			class dynamic3dAudio {};
			class dynamicDisguise {};
			class dynamicSimulation {};
			class editMissionProfileNamespace {};
			class editTerrainObjects {};
			class endMission {};
			class entitySpawner {};
			class equipableObject {};
			class execute {};
			class fultonExtract {};
			class generateSymbols {};
			class getClients {};
			class getDestinationTime {};
			class getDestinationVelocity {};
			class getGroupAttributes {};
			class getNearestSurface {};
			class getPosition {};
			class getRotation {};
			class getTransforms {};
			class getTriggerPresence {};
			class getUnitAttributes {};
			class getUnits {};
			class getVariableName {};
			class limitViewDistance {};
			class loadCargoInventories {};
			class loadControlAttributes {};
			class loadDisplay {};
			class loadMissionState {};
			class loadPlayerLoadouts {};
			class manageHandler {};
			class moduleAssignParachute {};
			class moduleBreakDisguise {};
			class moduleCameraSequence {};
			class moduleDisplaySubtitle {};
			class moduleDynamicDisguiseEquipment {};
			class moduleEditTerrainObjects {};
			class moduleEndMission {};
			class moduleEntitySpawner {};
			class modulePlayMusic {};
			class modulePlaySound2d {};
			class modulePlaySound3d {};
			class moduleSetAnimation {};
			class moduleSuspendMission {};
			class moduleTeleport {};
			class moduleVehicleSequence {};
			class openIdentificationCard {};
			class openRemoteInteractionMenu {};
			class openSelfInteractionMenu {};
			class openTerminal {};
			class orbitObject {};
			class removeEventHandler {};
			class recoverDisconnectedPlayers {};
			class respawnSpectator {};
			class saveCargoInventories {};
			class saveControlAttributes {};
			class saveMissionState {};
			class savePlayerLoadouts {};
			class setAnimation {};
			class setCameraTexture {};
			class setCurators {};
			class setDestinationVelocity {};
			class setGroupAttributes {};
			class setOwnership {};
			class setPersistentDisplayText {};
			class setPerspective {};
			class setPosition {};
			class setRandomLoadout {};
			class setRotation {};
			class setSideRelations {};
			class setTransforms {};
			class setUnitAttributes {};
			class setVideoTexture {};
			class suspendMission {};
			class teleport {};
			class toggleUserInput {};
			class vehicleSequence {};
			class unconsciousSpectator {};
			class visualTrigger {};
			class zeusModuleArma {};
			class zeusModuleBreakDisguise {};
			class zeusModuleClearStagedExecutions {};
			class zeusModuleRagdollUnit {};
			class zeusModuleStageExecution {};
			class zeusModuleSuspendMission {};
			class preStart {preStart = 1;};
			class preInit {preInit = 1;};
			class postInit {postInit = 1;};
		};
	};
};