#include "\x\kh\addons\main\resources\identificationCard.hpp"
#include "\x\kh\addons\main\resources\selfInteractionMenu.hpp"
#include "\x\kh\addons\main\resources\stageExecution.hpp"
#include "\x\kh\addons\main\resources\suspendMission.hpp"
#include "\x\kh\addons\main\resources\terminal.hpp"