params ["_unit"];

[
	hashValue _unit,
	[
		typeOf _unit,
		group _unit,
		vehicleVarName _unit,
		simulationEnabled _unit,
		dynamicSimulationEnabled _unit,
		isObjectHidden _unit,
		name _unit,
		face _unit,
		speaker _unit,
		pitch _unit,
		nameSound _unit,
		animationState _unit,
		gestureState _unit,
		getUnitMovesInfo _unit,
		rank _unit,
		rating _unit,
		stance _unit,
		unitPos _unit,
		pose _unit,
		isForcedWalk _unit,
		isTouchingGround _unit,
		((eyePos _unit) select 2) < 0,
		isSwitchingWeapon _unit,
		getUnitFreefallInfo _unit,
		getAnimSpeedCoef _unit,
		currentWeapon _unit,
		currentWeaponMode _unit,
		isWeaponDeployed _unit,
		currentMagazine _unit,
		currentThrowable _unit,
		currentVisionMode _unit,
		teamMember _unit,
		isAgent (teamMember _unit),
		formationLeader _unit,
		formLeader _unit,
		registeredTasks (teamMember _unit),
		currentTasks (teamMember _unit),
		captive _unit,
		getUnitLoadout _unit,
		getPosATL _unit,
		vectorDir _unit,
		vectorUp _unit,
		velocityModelSpace _unit,
		objectParent _unit,
		attachedTo _unit,
		attachedObjects _unit,
		damage _unit,
		getAllHitPointsDamage _unit,
		getBleedingRemaining _unit,
		getOxygenRemaining _unit,
		isDamageAllowed _unit,
		incapacitatedState _unit,
		lifeState _unit,
		unitRecoilCoefficient _unit,
		collisionDisabledWith _unit,
		unitCombatMode _unit,
		[
			skill _unit,
			_unit skill "aimingAccuracy",
			_unit skill "aimingShake",
			_unit skill "aimingSpeed",
			_unit skill "spotDistance",
			_unit skill "spotTime",
			_unit skill "courage",
			_unit skill "reloadSpeed",
			_unit skill "commanding",
			_unit skill "general"
		],
		[
			_unit checkAIFeature "AUTOTARGET",
			_unit checkAIFeature "MOVE",
			_unit checkAIFeature "TARGET",
			_unit checkAIFeature "TEAMSWITCH",
			_unit checkAIFeature "WEAPONAIM",
			_unit checkAIFeature "ANIM",
			_unit checkAIFeature "FSM",
			_unit checkAIFeature "AIMINGERROR",
			_unit checkAIFeature "SUPPRESSION",
			_unit checkAIFeature "CHECKVISIBLE",
			_unit checkAIFeature "AUTOCOMBAT",
			_unit checkAIFeature "COVER",
			_unit checkAIFeature "PATH",
			_unit checkAIFeature "MINEDETECTION",
			_unit checkAIFeature "LIGHTS",
			_unit checkAIFeature "NVG",
			_unit checkAIFeature "RADIOPROTOCOL",
			_unit checkAIFeature "FIREWEAPON"
		],
		getAllUnitTraits _unit,
		getEntityInfo _unit,
		synchronizedObjects _unit,
		_unit targetsQuery [objNull, sideUnknown, "", [], 0],
		allVariables _unit,
		_unit getVariable ["KH_var_initExecutions", []]
	]
];